name: Build
run-name: MyFiles engineer -> ${{ github.actor }} is working

on:
  pull_request:
  push:
    branches-ignore:
      - "layoff"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile --immutable --immutable-cache --check-cache
  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Lint with Prettier
        run: |
          # stop the build if there are Javascript or CSS syntax errors
          yarn format:check
  tests:
    needs: [build, lint]
    runs-on: ubuntu-latest
    steps:
      - name: Run Unit Tests
        run: yarn test:ci
  build-production:
    needs: [build, lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Create Production Build
        run: yarn run build:prod
      - name: Check Build Size & Generate Reports
        run: yarn run check-size
